### ISSUE TITLE
PATH set, yet padawan executable not found

### ISSUE THREAD

**Issue by Semmu** [mkusher/padawan.sublime#2]
I have set up my PATH so it includes the directory for padawan, yet this plugin (or Sublime Text itself) can't find the binary.

As you can see on my screenshot, the command padawan is recognized by my terminal emulator, but Sublime Text does not find it. (error message on the status bar)

![screenshot from 2015-11-13 00 30 50](https://cloud.githubusercontent.com/assets/1938602/11134536/dbade7a8-899d-11e5-9a45-97c7887bbf48.png)

**Comment by mkusher** [comment]
@Semmu I guess you set PATH in you `.zshrc` or `.bashrc` or so. If you start SublimeText from command line, will it find padawan executable?

**Comment by mkusher** [comment]
@Semmu have you managed to solve the issue?

**Comment by Semmu** [comment]
Yes and no. Starting it from a terminal does solve the issue, but I don't understand why doesn't Sublime Text have my envvars set automatically. I do it in my ~/.bash_aliases, which is included by ~/.bashrc, which is included by ~/.profile, so every process started by me should have it.

But this is not the issue of the plugin itself :)

**Comment by mkusher** [comment]
try in your `~/.bash_profile`

``` bash
PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH
```

**Comment by atapatel** [comment]
How to solve this issue in zsh Item2 terminal.

**Comment by mkusher** [comment]
@atapatel I guess you need to add path definition to `.zprofile` instead of `.bash_profile`

**Comment by elboletaire** [comment]
I have it set in `.zprofile`, `.zshrc`, and any other available `.z...` dotfile available in my home dir and it still doesn't find padawan. In my case all these files are symlinks which point to the original files located under `~/.dotfiles/${filename}`, but this should not be an issue (and if it's an issue, would be the first time).

How should I proceed to debug this?

**Comment by mkusher** [comment]
@elboletaire plugin doesn't make any magic, just creates subprocess. So, when in your terminal, running `echo $PATH` should output the right new PATH with composer bins in it

**Comment by elboletaire** [comment]
It does, but then sublime says padawan is not found in my path...

![imatge](https://cloud.githubusercontent.com/assets/153305/23855107/beed19d2-07f4-11e7-8a8f-c3e75147846c.png)

![imatge](https://cloud.githubusercontent.com/assets/153305/23855129/cfca9202-07f4-11e7-8a9e-816697e2b1c7.png)

**Comment by mkusher** [comment]
@elboletaire if you run sublime from terminal, then it'll work

**Comment by elboletaire** [comment]
That's not a solution 😕

**Comment by mkusher** [comment]
@elboletaire it only means, that the problem is not with the plugin, but with your env

**Comment by elboletaire** [comment]
Then... what's the solution? Should I add the `composer/vendor/bin` path to `/etc/environment`?

If so, why is this not stated in the readme file?

**Comment by elboletaire** [comment]
Oh, BTW, running from my command line works, but when trying to generate the index it says `Error occured, code 255`. But the console is empty, so can't get more information about the error...

![imatge](https://cloud.githubusercontent.com/assets/153305/23856110/9b10901c-07f8-11e7-8f22-174092325f82.png)

**Comment by elboletaire** [comment]
Ok, sorry for the last issue, I see in https://github.com/padawan-php/padawan.vim/issues/17 that it's a memory issue

**Comment by mkusher** [comment]
> Should I add the composer/vendor/bin path to /etc/environment?

adding to `~/.*profile` and re-loggining should be enough. There is a link to composer documentation on how to achieve it.

**Comment by mkusher** [comment]
~yeah, it was fixed here https://github.com/padawan-php/padawan.php/issues/47~
it is tracked by https://github.com/padawan-php/padawan.php/issues/42
